### ISSUE TITLE
No "R"ead All for CRUD?

### ISSUE THREAD

**Issue by c-myers1** [abivia/ledger#13]
I note you can only get a single item (resource) using the /get API routes. Is this deliberate?

**Comment by abivia** [comment]
Not explicitly. Can you give me a use case?

**Comment by c-myers1** [comment]
Standard CRUD. In building an admin panel around it all, you would want to see the list of resources (accounts, currencies, etc) and edit, delete, add another.

**Comment by abivia** [comment]
The accountQuery request handles accounts, but yes the functionality is missing for other resources. It's really more CRUDL with L for list.
I can see cases where you want to restrict access to "list" capability, which is one reason why accountQuery is a separate route. It makes sense to add this for other resources. I'll start work on that.

Thanks for pointing this out!

**Comment by abivia** [comment]
Code is in, hope to wrap documentation today and release.

**Comment by abivia** [comment]
Never say "hope to release today". Release 1.10.0 is out with a suite of query operations and improvements in existing queries. Updated [documentation](https://ledger.abivia.com) is available.

**Comment by c-myers1** [comment]
I didn’t notice any new stuff in the json api docs. E.g. which route returns all currencies?

**Comment by abivia** [comment]
Nuts. Updated the messages but not everything in the API. will fix. Generally {resource}/query will do the trick.

**Comment by abivia** [comment]
The navigation menu for the documentation was a manual process, and I missed updating that. Now it's automatic and all the new stuff is discoverable. There is still a problem with the codeselect JSON schema, but this has no operational impact.
