### ISSUE TITLE
Error in the example??

### ISSUE THREAD

**Issue by c-myers1** [abivia/ledger#3]
As I understand it with Abivia Ledger, a credit is always a positive ve amount whilst a debit is always a negative.

Consistent with this, In your example [here](https://ledger.abivia.com/getting-started/), Inventory was debited (-150) when stock was bought. 

Therefore, if I’m not muddling things up, when moving the sold value to COGS, it should be a credit (I.e. +10 not -10) to reduce Inventory. Given it’s a debit balance account, the Inventory account should show -140 not -160 after the transaction. COGS should normally carry a debit balance (an expense account) therefore it should be debited (-10 not +10) to increase expense.

Please confirm.

**Comment by abivia** [comment]
@c-myers1 You are correct. The example code and documentation have been corrected.

Good catch, thanks for bringing it to my attention!
