### ISSUE TITLE
PHP vs JSON API Completeness

### ISSUE THREAD

**Issue by c-myers1** [abivia/ledger#4]
Given the PHP API is more complete than the JSON API, please confirm: does it mean ALL functionality in the PHP is NOT yet available in the JSON? 

Or is it the case that JSON has all functionality already and only the documentation is WIP?

**Comment by abivia** [comment]
Can you be more specific? What are you seeing as not in the API?

**Comment by c-myers1** [comment]
Everything from this point down in the json api section of docs is blank. https://ledger.abivia.com/api/json/entryQuery/

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abivia** [comment]
Ah. Yes. The API should be complete. The docs are still a work in progress. In the interim the best source is the tests.

**Comment by abivia** [comment]
The API docs have been updated and should now be complete.
